# Generated by Django 5.1.2 on 2024-11-04 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
